# [Assignment 3: Data Integration & Data Preparation](https://hqahtan.github.io/Teaching/infomdw/assignments/Assignment_3_26_27.html)

In [1]:
%pip install pandas

Requirement already satisfied: pandas in c:\Users\ossam\anaconda3\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\ossam\anaconda3\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\ossam\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\ossam\anaconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\Users\ossam\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
# Load ACM and DBLP2 datasets into pandas DataFrames
acm = pd.read_csv("./raw/acm.csv", encoding="ISO-8859-1")
dblp2 = pd.read_csv("./raw/DBLP2.csv", encoding="ISO-8859-1")

### Display the data

In [4]:
acm.head()

,id,title,authors,venue,year
0,304586,The WASA2 object-oriented workflow management ...,"Gottfried Vossen, Mathias Weske",International Conference on Management of Data,1999
1,304587,A user-centered interface for querying distrib...,"Isabel F. Cruz, Kimberly M. James",International Conference on Management of Data,1999
2,304589,"World Wide Database-integrating the Web, CORBA...","Athman Bouguettaya, Boualem Benatallah, Lily H...",International Conference on Management of Data,1999
3,304590,XML-based information mediation with MIX,"Chaitan Baru, Amarnath Gupta, Bertram Lud&#228...",International Conference on Management of Data,1999
4,304582,The CCUBE constraint object-oriented database ...,"Alexander Brodsky, Victor E. Segal, Jia Chen, ...",International Conference on Management of Data,1999

In [5]:
dblp2.head()

,id,title,authors,venue,year
0,journals/sigmod/Mackay99,Semantic Integration of Environmental Models f...,D. Scott Mackay,SIGMOD Record,1999
1,conf/vldb/PoosalaI96,Estimation of Query-Result Distribution and it...,"Viswanath Poosala, Yannis E. Ioannidis",VLDB,1996
2,conf/vldb/PalpanasSCP02,Incremental Maintenance for Non-Distributive A...,"Themistoklis Palpanas, Richard Sidle, Hamid Pi...",VLDB,2002
3,conf/vldb/GardarinGT96,Cost-based Selection of Path Expression Proces...,"Zhao-Hui Tang, Georges Gardarin, Jean-Robert G...",VLDB,1996
4,conf/vldb/HoelS95,Benchmarking Spatial Join Operations with Spat...,"Erik G. Hoel, Hanan Samet",VLDB,1995

## Task 1: Record Matching 

### Data cleaning

In [9]:
def clean_strings(value: any) -> any:
    if isinstance(value, str):
        # 1. Change all alphabetical characters into lowercase for Pandas dataframe values
        value = value.lower()
        # 2. Eliminate extra spaces by trimming leading and trailing spaces
        value = value.strip()
        # 3. Replace consecutive whitespaces with a single space
        value = " ".join(value.split())
    return value


# Perform string cleaning on the datasets
acm = acm.map(clean_strings)
dblp2 = dblp2.map(clean_strings)

### Levenshtein similarity

### Jaro similarity